/-
# `SgsLean/Server.lean`：stdio JSON 服务（协议 v1）

Python 侧唯一入口，协议见 `docs/implementation-blueprint.md`。要点：

* **传输**：stdin / stdout 各一行一条 JSON（JSONL），UTF-8；诊断只走 stderr，
  **stdout 只放响应**，调用方可以放心逐行 `json.loads`。
* **命令**：`ping` / `check` / `verify` / `cheap` / `flush`。写若干条请求后发 `{"cmd":"flush"}` 取回本批响应，
  或在 EOF 时自动 flush；每条请求恰好一条响应，顺序与请求一致。
* **判定**：直接复用 P1.1 的 `Gate.check` / `Verify.verify`（`TacticM`），服务端与库内同源。

## 执行模型：每批 spawn 一个 `lean` 子进程

`Gate` / `Verify` 是 `TacticM` 动作，需要 elaboration 上下文，而 standalone 可执行文件里没有环境。
父进程（本文件编译出的 `sgslean-server`）因此：

1. 在工作目录写 `jobs.json`（本批请求）与 `sgslean_snippet.lean`（**内容固定**的片段）；
2. `spawn` 一个 `lean sgslean_snippet.lean` 子进程（`cwd` = 工作目录）；
3. 片段里的 `run_tac SgsLean.Server.runJobs` 读 `jobs.json`、逐条判定、把响应数组写 `out.json`；
4. 父进程读 `out.json`，逐条回响应。

工作目录里还有一份 `lean-toolchain`，保证 elan 在 `cwd` 下选出**与项目一致**的工具链
（否则会落到 elan 默认工具链上，版本不匹配）。

为什么不是进程内 `Lean.Elab.runFrontend`（P1.2 首版做法，已废弃）：

* 导入 Mathlib 时进程内 frontend 直接崩：`cannot evaluate [init] declaration
  'Mathlib.pp.mathlib.binderPredicates' in the same module`；换成 `lean` 驱动（Mathlib 开发的
  标准姿势）就正常了；
* frontend 的消息默认打到 **stdout**（`IO.print`），会污染协议流；子进程方案把孩子进程的
  stdout/stderr 一起挂到父进程的 stderr 上，协议流天然干净；
* 子进程崩溃不会带走服务进程（首版 Mathlib 导入崩溃时整个 server 都没了）。

代价：每批多一次进程启动（≈1–2 s）；Mathlib 模式下一次批处理的固定成本 = 导入 Mathlib
（本机实测 ≈100–420 s，冷热差异大）。所以**必须批量喂请求**，别一条一条走。
-/
import SgsLean

open Lean

namespace SgsLean.Server

/-- 协议版本。

v1.2：`ping` 回报实际生效的判定预算（心跳 / 秒杀心跳 / 单 tactic 墙钟），
子进程的 `maxHeartbeats` 与 `reap.timeout` 由环境变量注入。
起因：miniF2F 的 G1 里 74% 的失败是 `exception`，必须能不改代码地把预算放大来分离
"模型证不出"与"预算掐死"（见 `docs/phase18-log.md`）。 -/
def protocolVersion : String := "v1.2"

/-- 读一个 Nat 型环境变量，解析失败或缺失则退回默认值。 -/
def envNat (name : String) (fallback : Nat) : IO Nat := do
  match ← IO.getEnv name with
  | some raw => return (raw.trimAscii.toString.toNat?).getD fallback
  | none => return fallback

/-- 子进程判定心跳的默认值（与 `SgsLean.defaultHeartbeats` 保持一致）。 -/
def defaultHeartbeats : Nat := 4000000
/-- 秒杀心跳的默认值（与 `SgsLean.Trivial.defaultHeartbeats` 保持一致）。 -/
def defaultTrivialHeartbeats : Nat := 200000
/-- 单 tactic 墙钟上限的默认值（毫秒，与 reap 的 `reap.timeout` 默认一致）。 -/
def defaultTacticTimeoutMs : Nat := 200000

/-- 工作目录里的三个文件（片段固定用相对名，父进程把 `cwd` 设为工作目录）。 -/
def snippetFileName : String := "sgslean_snippet.lean"
def jobsFileName : String := "jobs.json"
def outFileName : String := "out.json"
/-- 子进程的启动脚本（把 lean 的输出重定向到 child.log）。 -/
def childCmdFileName : String := "run_child.cmd"

/-- 子进程默认导入的库。`SGSLEAN_IMPORTS=none` 切回无 Mathlib 的快速模式。

注意不能用空串表示"不导入"：Windows 上把环境变量设成空串等于**删除**该变量
（`SetEnvironmentVariable(name, "")` 的语义），父进程会退回默认值。实测踩过：
Python 侧 `os.environ["SGSLEAN_IMPORTS"] = ""` 后，服务端仍按默认的 `Mathlib` 跑。 -/
def defaultImports : String := "Mathlib"

/-- 自动生成的库模块。它由 `Materialize` 写盘，**绝不能**出现在生成文件自己的 import 里
    （否则是自我循环导入）。 -/
def generatedLibraryModule : String := "SgsLean.GeneratedLibrary"

/-- 解析 import 列表；`none`/`-` 表示"不额外导入任何库"。 -/
def parseImports (raw : String) : Array String :=
  let trimmed := raw.trimAscii.toString
  if trimmed == "none" || trimmed == "-" then #[]
  else (trimmed.splitOn "," |>.map (fun s => s.trimAscii.toString) |>.filter (fun s => !s.isEmpty)).toArray

private def okResponse (id : Json) (result : Json) : Json :=
  Json.mkObj [("id", id), ("ok", Json.bool true), ("result", result)]

private def errResponse (id : Json) (code message : String) : Json :=
  Json.mkObj [
    ("id", id),
    ("ok", Json.bool false),
    ("error", Json.mkObj [("code", toJson code), ("message", toJson message)])]

/-! ## 子进程侧：判定层（meta，直接复用 Gate / Verify） -/

meta section

open Lean Meta Elab Tactic

/-- `ping` 的答案：**子进程**里真实加载了什么（调用方据此判断能否做 Mathlib 级判定）。
注意 ping 也是一条作业，因此它要跑一次 frontend（Mathlib 模式下就是一次完整导入）。 -/
def environmentInfo : TacticM Json := do
  let env ← getEnv
  return Json.mkObj [
    ("status", toJson "ok"),
    ("version", toJson protocolVersion),
    ("importedModules", toJson env.header.moduleNames.size),
    ("mathlib", toJson (env.header.moduleNames.any (fun n => n == `Mathlib))),
    -- 判定预算也回报：G1/诊断的结论必须能带上"用的是哪个预算"，否则数字不可比。
    ("heartbeats", toJson (← getHeartbeats)),
    ("trivialHeartbeats", toJson (← Trivial.getTrivialHeartbeats)),
    ("cheapBatches", toJson (Trivial.cheapBatches.map fun b => b.tactics.size)),
    ("tacticTimeoutMs", toJson (reap.timeout.get (← getOptions)))]

/-- 编译器自动生成的名字（`match_…` / `proof_…` / `_uniq.…`）：不是"可复用的 folklore 引理"，
    在挑 C2 语料时要排除，否则会把一堆内部辅助定理当成课程集题目。 -/
def isAutoGenerated (name : Name) : Bool :=
  let s := name.toString
  name.isInternal || s.contains "_uniq." || s.contains ".proof_" || s.contains ".match_"
    || s.contains "_proof_1" || s.contains "._proof"

/-- 列出环境里"语句是命题"的**定理**（名字 + 类型文本 + 所属模块），按模块前缀分桶。

用途：构建 C2 课程集（`docs/data-protocol.md` 的"从 Mathlib 取定理"），
见 `tools/prepare_domain_corpus.py`。**一次遍历环境、多个前缀分桶**——环境遍历
（几十万个常量）是这条命令的主要成本，按前缀发多条作业会把它重复付 N 遍
（实测：7 个前缀 ×2.5 分钟，且 `Mathlib.Order` 这种超大命名空间会拖到十几分钟）。

三条过滤写在返回体里，调用方可复核：

* 跳过编译器自动生成的名字（`isAutoGenerated`）；
* 跳过**宇宙多态**定理（`levelParams` 非空）：它们的 pp 文本里有 `u`，回代时是未绑定层
  （`Gate.check` 必然拒绝，不如早点省掉 pp 的开销）；
* pp 文本超过 `maxTypeLen` 字符或含 `?`（占位符不可回代）的丢掉，并计数。

每个前缀内部按名字排序后取前 `perPrefixLimit` 条（**可复现**）。
**只负责"列出"**：能不能 elaborate、"是不是命题"由 `check` 判定。 -/
def listTheorems (prefixes : Array String) (perPrefixLimit maxTypeLen : Nat) : TacticM Json := do
  let env ← getEnv
  let wanted := prefixes.map (fun m => m.trimAscii.toString) |>.filter (fun m => !m.isEmpty)
  let mut buckets : Array (Array Name) := wanted.map (fun _ => #[])
  for (name, info) in env.constants.toList do
    if let .thmInfo info := info then
      unless isAutoGenerated name do
        if info.levelParams.isEmpty then
          let modName : String :=
            match env.getModuleIdxFor? name with
            | some idx => (env.header.moduleNames[idx]?.map (·.toString)).getD ""
            | none => ""
          for i in [:wanted.size] do
            let w := wanted[i]!
            if modName == w || modName.startsWith (w ++ ".") then
              buckets := buckets.set! i (buckets[i]!.push name)
  let mut groups : Array Json := #[]
  for i in [:wanted.size] do
    let sorted := buckets[i]!.qsort (fun a b => a.toString < b.toString)
    let sliced := sorted.extract 0 (min sorted.size perPrefixLimit)
    let mut out : Array Json := #[]
    let mut dropped := 0
    for name in sliced do
      match env.find? name with
      | some (.thmInfo info) =>
        let tyText := toString (← ppExpr info.type)
        if tyText.length <= maxTypeLen && !tyText.contains '?' then
          let modName : String :=
            match env.getModuleIdxFor? name with
            | some idx => (env.header.moduleNames[idx]?.map (·.toString)).getD ""
            | none => ""
          out := out.push (Json.mkObj [
            ("name", toJson name.toString), ("type", toJson tyText), ("module", toJson modName)])
        else
          dropped := dropped + 1
      | _ => dropped := dropped + 1
    groups := groups.push (Json.mkObj [
      ("prefix", toJson wanted[i]!), ("total", toJson sorted.size),
      ("count", toJson out.size), ("dropped", toJson dropped), ("theorems", Json.arr out)])
  return Json.mkObj [("count", toJson groups.size), ("groups", Json.arr groups)]

/-- 处理一条请求 → 一条响应。任何内部失败都变成 `internal_error`，不向外抛。 -/
def handleJob (job : Json) : TacticM Json := do
  let id := job.getObjValD "id"
  let cmd := (job.getObjValAs? String "cmd").toOption.getD ""
  try
    match cmd with
    | "ping" => return okResponse id (← environmentInfo)
    | "check" =>
      match (job.getObjValAs? String "stmt").toOption with
      | none => return errResponse id "invalid_params" "check 需要字符串字段 stmt"
      | some stmt => return okResponse id (toJson (← Gate.check stmt))
    | "verify" =>
      match (job.getObjValAs? String "stmt").toOption, (job.getObjValAs? String "proof").toOption with
      | some stmt, some proof => return okResponse id (toJson (← Verify.verify stmt proof))
      | _, _ => return errResponse id "invalid_params" "verify 需要字符串字段 stmt 与 proof"
    | "trace" =>
      match (job.getObjValAs? String "stmt").toOption, (job.getObjValAs? String "proof").toOption with
      | some stmt, some proof => return okResponse id (toJson (← Trace.traceScript stmt proof))
      | _, _ => return errResponse id "invalid_params" "trace 需要字符串字段 stmt 与 proof"
    | "trivial" =>
      match (job.getObjValAs? String "stmt").toOption with
      | some stmt => return okResponse id (toJson (← Trivial.isTrivial stmt))
      | none => return errResponse id "invalid_params" "trivial 需要字符串字段 stmt"
    | "cheap" =>
      match (job.getObjValAs? String "stmt").toOption with
      | some stmt => return okResponse id (toJson (← Trivial.tryCheapTactics stmt))
      | none => return errResponse id "invalid_params" "cheap 需要字符串字段 stmt"
    | "cheap_verify" =>
      -- 廉价兜底 + **对它命中的那条 tactic** 的内核终检，一次作业完成。
      --
      -- 为什么必须合成一个命令：调用方发批的时候还不知道会命中哪条 tactic，
      -- 那时唯一的 `proof` 只能是空串；把 `verify(proof="")` 和 `cheap` 塞进同一批
      -- 就会拿空串的判定去裁定命中的 tactic（恒 `parse_error`），兜底彻底失效
      -- （实测：`cheap` 报 `hit=true, tactic=simp`，`verify("")` 报 `ok=false`）。
      match (job.getObjValAs? String "stmt").toOption with
      | none => return errResponse id "invalid_params" "cheap_verify 需要字符串字段 stmt"
      | some stmt =>
        let cheap ← Trivial.tryCheapTactics stmt
        -- 没命中就没有可终检的脚本，`verify` 回空对象（调用方据此知道"没得判"，
        -- 而不是把它当成"判过且失败"）。
        let verifyJson : Json ←
          if cheap.hit && !cheap.proof.isEmpty then
            toJson <$> Verify.verify stmt cheap.proof
          else
            pure (Json.mkObj [])
        return okResponse id (Json.mkObj [("cheap", toJson cheap), ("verify", verifyJson)])
    | "novelty" =>
      match (job.getObjValAs? String "stmt").toOption with
      | none => return errResponse id "invalid_params" "novelty 需要字符串字段 stmt"
      | some stmt =>
        let against := (job.getObjValAs? (Array String) "against").toOption.getD #[]
        return okResponse id (toJson (← Novelty.isNew stmt against))
    | "compression" =>
      match (job.getObjValAs? String "stmt").toOption,
            (job.getObjValAs? String "longProof").toOption,
            (job.getObjValAs? String "shortProof").toOption with
      | some stmt, some longProof, some shortProof =>
        return okResponse id (toJson (← Measure.compression stmt longProof shortProof))
      | _, _, _ => return errResponse id "invalid_params" "compression 需要 stmt/longProof/shortProof"
    | "dependencies" =>
      match (job.getObjValAs? String "stmt").toOption, (job.getObjValAs? String "proof").toOption with
      | some stmt, some proof =>
        let target := (job.getObjValAs? String "target").toOption.getD ""
        return okResponse id (toJson (← Measure.dependencies stmt proof target))
      | _, _ => return errResponse id "invalid_params" "dependencies 需要字符串字段 stmt 与 proof"
    | "materialize" =>
      match (job.getObjValAs? String "path").toOption,
            (job.getObjValAs? (Array LemmaEntry) "entries").toOption with
      | some path, some entries =>
        let raw := (← IO.getEnv "SGSLEAN_IMPORTS").getD defaultImports
        -- **必须把自己剔掉**：处理臂启动时 `SGSLEAN_IMPORTS=Mathlib,SgsLean.GeneratedLibrary`，
        -- 若照抄进生成文件的头部，生成的文件就 import 它自己 ⟹ 循环导入、编译失败
        -- （实测：闭环第一轮在 commit 的编译校验处停住；库已写入但物化文件编不过，
        -- 下一轮的 import 必然失败——正是 phase22/26 记的"库没用"那类假象）。
        let mods := parseImports raw |>.filter (fun m => m != generatedLibraryModule)
        let result ← Materialize.emit path entries mods
        return okResponse id (toJson result)
      | _, _ => return errResponse id "invalid_params" "materialize 需要 path 与 entries"
    | "list_theorems" =>
      let prefixes := (job.getObjValAs? (Array String) "prefixes").toOption.getD #[]
      let perPrefixLimit := (job.getObjValAs? Nat "perPrefixLimit").toOption.getD 200
      let maxTypeLen := (job.getObjValAs? Nat "maxTypeLen").toOption.getD 400
      return okResponse id (← listTheorems prefixes perPrefixLimit maxTypeLen)
    | _ => return errResponse id "bad_request" s!"unknown cmd: {repr cmd}"
  catch ex =>
    return errResponse id "internal_error" (← ex.toMessageData.toString)

/-- 读 `jobs.json`（JSON 数组）。 -/
def readJobs : IO (Array Json) := do
  let text ← IO.FS.readFile jobsFileName
  return (Json.parse text).toOption.bind (fun j => j.getArr?.toOption) |>.getD #[]

/-- 某个作业的响应已经落盘了吗（父进程据此判断这一条是否已完成）。 -/
def responsesSoFar : IO (Array Json) := do
  match ← (try some <$> IO.FS.readFile outFileName catch _ => pure none) with
  | none => return #[]
  | some text =>
    match Json.parse text with
    | .ok json => return json.getArr?.toOption.getD #[]
    | .error _ => return #[]

/-- **子进程入口**：判定 `jobs.json` 里的**第 `index` 条**作业，把响应数组写回 `out.json`。

为什么是"一条作业一个 command"（而不是以前的一次 `run_tac` 跑完整批）：

* Lean 的心跳预算**按 command 累计**（`Lean.Elab.Command` 在每个 command 开头记录
  `initHeartbeats`）。整批挤在一个 `run_tac` 里 ⟹ 后面几十条作业共享前面作业的消耗，
  批次尾部集体报 `maximum number of heartbeats`，看起来像"模型证不出"——
  phase18/19/20 都踩过，只能靠 `budget_for_jobs` 这个经验公式硬撑。
  一条作业一个 command，计数器**自动复位**，这类伪影从根上消失。
* 每条作业的失败（心跳耗尽、tactic 抛异常）只影响它自己的 command，
  父进程仍然能拿到其余条目的结果。

响应**逐条落盘**（写完这条就写文件）：只要有一条让子进程硬崩，损失也限制在它自己，
父进程侧对缺失条目回"响应缺失"，剩下的结果仍然可用。 -/
def runJob (index : Nat) : TacticM Unit := do
  let jobs ← readJobs
  let some job := jobs[index]? | return ()
  let out ← responsesSoFar
  -- 只为兼容"父进程把响应数组按位置对齐"的约定：缺位补空对象。
  let mut out := out
  while out.size < index do
    out := out.push (Json.mkObj [])
  let response ← handleJob job
  if out.size == index then
    out := out.push response
  else
    out := out.set! index response
  IO.FS.writeFile outFileName (Json.arr out).compress

/-- 一次判定整批（保留给"作业数未知"的调用方；服务端主路径用 `runJob`）。 -/
def runJobs : TacticM Unit := do
  let jobs ← readJobs
  for index in [:jobs.size] do
    runJob index

end

/-! ## 父进程侧：片段生成、子进程调度、主循环 -/

/-- 片段源码：**形状固定**（import 头与判定预算由环境配置决定，请求数据永不参与拼字符串）。

每个作业一个 `example` command：心跳计数器按 command 复位，批次尾部不再被前面的作业
拖死（见 `runJob` 的说明）。`nJobs` 只决定重复几个 command，不插入任何请求内容。 -/
def snippetSource (imports : String) (heartbeats tacticTimeoutMs : Nat) (nJobs : Nat) : String :=
  let mods := parseImports imports
  -- 没有 Mathlib 时要自己补 `ℕ` 记法；有 Mathlib 时**不能**补（重复声明 termℕ 是硬错误）
  let notationPatch := if mods.contains "Mathlib" then #[] else #["import SgsLean.Syntax"]
  -- `linter.unusedTactic` 是 Mathlib 提供的 linter；核心环境里没这个选项，设了会直接报错
  let linterPatch := if mods.contains "Mathlib" then #["  set_option linter.unusedTactic false"] else #[]
  -- miniF2F 的题面假定这些名字空间是打开的（原文件头就写着 `open BigOperators Real
  -- Nat Topology Rat`）。判定环境以前没有它们，于是 `π`、`∑` 这类记法被判
  -- `unknown_identifier` / `parse_error`，D/T 各丢了十几条题——那是环境缺失，不是数学错。
  let opensPatch :=
    if mods.contains "Mathlib" then #["open BigOperators Real Nat Topology Rat"] else #[]
  let header := (mods.map (fun m => s!"import {m}")) ++ notationPatch ++
    #["import SgsLean", "import SgsLean.Server"]
  let body := (List.range nJobs).map fun i =>
    s!"example : True := by\n  run_tac (SgsLean.Server.runJob {i})\n  trivial"
  String.intercalate "\n" ((header ++ opensPatch ++ #[
    "open Lean Meta Elab Tactic",
    "set_option autoImplicit true",
    "set_option Elab.async false",
    -- **关掉 Lean 的错误上限**（默认 `maxErrors = 100`）。一个作业一个 command 之后，
    -- 失败作业的错误会累加到**同一个文件**的消息表里：一旦累计到 100，Lean 直接
    -- `maximum number of errors (100; from option maxErrors) reached, exiting`，
    -- 后面的 command 一个都不跑 ⟹ 父进程对它们回"响应缺失"，而调用方会把它误读成
    -- "这些候选没过门检"。实测：156 个作业的硬门批只回了 51 条，2/3 的候选被静默丢掉。
    -- 0 = 不限制；每条作业的成败由 `handleJob` 自己如实回报。
    "set_option maxErrors 0",
    -- 这两个值来自环境变量，缺省与库里的默认常量一致。
    s!"set_option maxHeartbeats {heartbeats}",
    -- 单 tactic 的墙钟上限：Mathlib 级 tactic 在解释执行下偶发很慢，
    -- 心跳管住 CPU 预算、墙钟兜住 IO/解释器开销，两者要一起调。
    s!"set_option reap.timeout {tacticTimeoutMs}"] ++ linterPatch ++ #[
    ""] ++ body ++ [""]).toList)

/-- 项目工具链字符串（写进工作目录的 `lean-toolchain`，让 elan 选对版本）。 -/
def projectToolchain : IO String := do
  try
    return (← IO.FS.readFile "lean-toolchain").trimAscii.toString
  catch _ =>
    return "leanprover/lean4:v4.28.0-rc1"

/-- 准备工作目录：片段 + 工具链 + 记录用信息。 -/
def prepareWorkDir : IO System.FilePath := do
  let dir : System.FilePath :=
    match (← IO.getEnv "SGSLEAN_WORKDIR") with
    | some p => p
    | none => ".lake" / "sgslean-server-work"
  IO.FS.createDirAll dir
  IO.FS.writeFile (dir / "lean-toolchain") ((← projectToolchain) ++ "\n")
  -- 片段**每批**重写（内容只依赖 import/预算/作业条数），所以这里不再写它——
  -- 见 `runBatch`。工作目录里仍然要有 lean-toolchain 与启动脚本。
  -- 用脚本文件承载重定向：`cmd /c` 的参数里带空格/重定向符时，Lean 的 spawn 会加引号，
  -- 实测传过去就不是 cmd 想要的语法（exit=1、日志也没生成）。写进 .cmd 最稳。
  IO.FS.writeFile (dir / childCmdFileName)
    s!"@echo off\r\nlean {snippetFileName} > child.log 2>&1\r\n"
  return dir

/-- 跑一批作业：写 `jobs.json` → spawn `lean` → 读 `out.json`。
返回（与 `jobs` 等长的响应数组，子进程耗时毫秒）。 -/
def runBatch (jobs : Array Json) (workDir : System.FilePath) : IO (Array Json × Nat) := do
  if jobs.isEmpty then return (#[], 0)
  IO.FS.writeFile (workDir / jobsFileName) (Json.arr jobs).compress
  -- 每批重写片段：一个作业一个 command（心跳按 command 复位），作业条数决定 command 数。
  let imports := (← IO.getEnv "SGSLEAN_IMPORTS").getD defaultImports
  let heartbeats ← envNat "SGSLEAN_HEARTBEATS" defaultHeartbeats
  let tacticTimeoutMs ← envNat "SGSLEAN_TACTIC_TIMEOUT_MS" defaultTacticTimeoutMs
  IO.FS.writeFile (workDir / snippetFileName)
    (snippetSource imports heartbeats tacticTimeoutMs jobs.size)
  let outPath := workDir / outFileName
  try IO.FS.removeFile outPath catch _ => pure ()
  let start ← IO.monoNanosNow
  -- 子进程输出用 **shell 重定向**落到 child.log：
  -- `IO.withStdout` 只改 Lean 层的流，改不了子进程继承的 OS 句柄（实测子进程的错误消息
  -- 会直接漏进 stdout，破坏协议）；`.piped` 又会被 Lean 按 UTF-8 解码（中文环境的
  -- bsdtar/curl 输出会触发 `non UTF-8 data` panic），所以交给 cmd.exe 重定向最稳。
  let exitCode ← do
    let child ← IO.Process.spawn {
      cmd := "cmd.exe"
      args := #["/c", childCmdFileName]
      cwd := some workDir
      stdin := .null
      stdout := .null
      stderr := .null
    }
    child.wait
  let stop ← IO.monoNanosNow
  let elapsedMs := (stop - start) / 1000000
  let failure := fun () =>
    jobs.map fun job =>
      errResponse (job.getObjValD "id") "internal_error"
        s!"lean 子进程未产出结果（exit={exitCode}）；\
           工作目录 {workDir.toString} 里有 {snippetFileName}/{jobsFileName} 可手工复现，\
           诊断见同目录 child.log"
  match (← (try some <$> IO.FS.readFile outPath catch _ => pure none)) with
  | none => return (failure (), elapsedMs)
  | some text =>
    match Json.parse text with
    | .ok json => return ((json.getArr?.toOption.getD #[]), elapsedMs)
    | .error _ => return (failure (), elapsedMs)

/-- 打印一批响应：`batch` 里每一条作业恰好一条响应，顺序一致。返回（条数，子进程毫秒）。 -/
private def flushBatch (workDir : System.FilePath) (batch : Array Json) : IO (Nat × Nat) := do
  let stdout ← IO.getStdout
  let (responses, elapsedMs) ← runBatch batch workDir
  let mut out : Array String := #[]
  let mut idx := 0
  for job in batch do
    match responses[idx]? with
    | some r => out := out.push r.compress
    | none => out := out.push (errResponse (job.getObjValD "id") "internal_error" "响应缺失").compress
    idx := idx + 1
  for line in out do
    stdout.putStrLn line
  stdout.flush
  return (out.size, elapsedMs)

/-- 主循环：读 JSONL 请求，按批 flush，逐条回响应。 -/
def mainLoop : IO Unit := do
  let stdin ← IO.getStdin
  let stdout ← IO.getStdout
  let workDir ← prepareWorkDir
  let mut batch : Array Json := #[]
  let mut running := true
  while running do
    let line ← stdin.getLine
    if line.isEmpty then
      running := false
      let _ ← flushBatch workDir batch
    else
      let trimmed := line.trimAscii.toString
      if trimmed.isEmpty then
        pure ()
      else
        -- 只有"JSON 对象"才算请求；其它情况一律立刻回 bad_request（这类响应没有可回填的 id）
        match Json.parse trimmed with
        | .error msg =>
          stdout.putStrLn (errResponse Json.null "bad_request" s!"invalid JSON line: {msg}").compress
          stdout.flush
        | .ok json =>
          match json with
          | .obj _ =>
            if ((json.getObjValAs? String "cmd").toOption.getD "") == "flush" then
              let (n, elapsedMs) ← flushBatch workDir batch
              batch := #[]
              stdout.putStrLn (okResponse (json.getObjValD "id")
                (Json.mkObj [("flushed", toJson n), ("frontend_ms", toJson elapsedMs)])).compress
              stdout.flush
            else
              batch := batch.push json
          | _ =>
            stdout.putStrLn (errResponse Json.null "bad_request" "请求必须是 JSON 对象").compress
            stdout.flush

end SgsLean.Server

/-- 可执行入口（`lake exe sgslean-server`）。 -/
def main : IO Unit := SgsLean.Server.mainLoop
